### ISSUE TITLE
Chatterbot attribute error: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by M-G-C-64** [gunthercox/ChatterBot#2122]

**Comment by M-G-C-64** [comment]
> _No description provided._

**Comment by M-G-C-64** [comment]
So I literally pasted the code from the official website (using VScode) and it shows no problems but gets an attribute error while running

#code:
from chatterbot import ChatBot
chatbot = ChatBot("Ron Obvious")

from chatterbot.trainers import ListTrainer

conversation = [
    "Hello",
    "Hi there!",
    "How are you doing?",
    "I'm doing great.",
    "That is good to hear",
    "Thank you.",
    "You're welcome."
]

trainer = ListTrainer(chatbot)
trainer.train(conversation)

response = chatbot.get_response("Good morning!")
print(response)


error:
Traceback (most recent call last):
  File "c:/Users/anilm/G/Python/projects/Chatbot/chatbottt.py", line 22, in <module>
    chatbot = ChatBot("Ron Obvious")
  File "C:\Users\anilm\AppData\Local\Programs\Python\Python38-32\lib\site-packages\chatterbot\chatterbot.py", line 41, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)      
  File "C:\Users\anilm\AppData\Local\Programs\Python\Python38-32\lib\site-packages\chatterbot\utils.py", line 54, in initialize_class
    return Class(*args, **kwargs)
  File "C:\Users\anilm\AppData\Local\Programs\Python\Python38-32\lib\site-packages\chatterbot\storage\sql_storage.py", line 22, in __init__
    from sqlalchemy import create_engine
  File "C:\Users\anilm\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\__init__.py", line 8, in <module>
    from . import util as _util  # noqa
  File "C:\Users\anilm\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\util\__init__.py", line 14, in <module>
    from ._collections import coerce_generator_arg  # noqa
  File "C:\Users\anilm\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\util\_collections.py", line 16, in <module>
    from .compat import binary_types
  File "C:\Users\anilm\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\util\compat.py", line 264, in <module>
    time_func = time.clock
AttributeError: module 'time' has no attribute 'clock'

**Comment by daniyalas** [comment]
I am getting the same error and am just as confused.

**Comment by Derleek22** [comment]
I also had this issue. It happens because time.clock depreciated after 3.8 (i think). I fixed it by going into the compat.py file and switching time.clock to time.time. I'm not sure if it will mess with anything else, but from what i understand it has the same function and works in 3.9

**Comment by AnAnalogGuy** [comment]
@Derleek22 If you have a fix, you might want to contribute a pull request?
