### ISSUE TITLE
Error on running python manage.py runserver 0.0.0.0:8000

### ISSUE THREAD

**Issue by jays1** [gunthercox/ChatterBot#1002]
I am getting the below mentioned error when running the server. Has anybody experienced it ?

Python 3.6.1 :: Anaconda 4.4.0 (64-bit)
Django 2.1.dev20170928183954
chatterbot 0.7.6

on running >>>>>>
C:\Users\JS\scrapy\ChatterBot\examples\django_app>python manage.py runserver 0.0.0.0:8000
>>>>>>>>>>>>>

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x000001C67A937510>
Traceback (most recent call last):
  File "c:\users\js\scrapy\django\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "c:\users\js\scrapy\django\django\core\management\commands\runserver.py", line 112, in inner_run
    autoreload.raise_last_exception()
  File "c:\users\js\scrapy\django\django\utils\autoreload.py", line 248, in raise_last_exception
    raise _exception[0](_exception[1]).with_traceback(_exception[2])
  File "c:\users\js\scrapy\django\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "c:\users\js\scrapy\django\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "c:\users\js\scrapy\django\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "c:\users\js\scrapy\django\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\JS\AppData\Local\Continuum\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\JS\AppData\Local\Continuum\Anaconda3\lib\site-packages\chatterbot\ext\django_chatterbot\models.py", line 123, in <module>
    class AbstractBaseResponse(models.Model):
  File "C:\Users\JS\AppData\Local\Continuum\Anaconda3\lib\site-packages\chatterbot\ext\django_chatterbot\models.py", line 132, in AbstractBaseResponse
    related_name='in_response'
TypeError: __init__() missing 1 required positional argument: 'on_delete'

**Comment by gunthercox** [comment]
Hi @jays1, I believe you are running Django 2.0 (which is currently in an alpha release state). ChatterBot doesn't support Django 2.0 yet.

To fix this problem you can install the latest current version of Django.

```
pip install django<2.0
```

**Comment by gunthercox** [comment]
I'm fairly certain I know the cause of this error and I will be making a changes in the near future to support Django 2.0

**Comment by jays1** [comment]
Thanks for your input. Is there any recommended version of Django that I should be using ? I tried installing 1.9 and getting a different error (HTMLParseError) on starting the server.

**Comment by jays1** [comment]
Thanks it worked with Django 1.11.5
