### ISSUE TITLE
'ChatBot' object has no attribute 'find' Again..

### ISSUE THREAD

**Issue by tomy300** [gunthercox/ChatterBot#1695]
Hello, here my case... I know this issue was talk about before and discute

I don't know if I will be able to use chatterbot, I have a robot Nao that work on old python 2.7, I just can't update python to a newer version because the system file of the robot will not work. I ask for an update but SoftBank didn't have interest to make it so. also the system have only 1gig space.. so we are very limited on what we can do. however... I would really wish to try this bot.. I don't want to build one myself..

I have installed the version 0.8.6

here the error message

`  File "bot.py", line 20, in <module>
    trainer.train(conversation)
  File "/usr/lib/python2.7/site-packages/ChatterBot-0.8.6-py2.7.egg/chatterbot/trainers.py", line 110, in train
    statement = self.get_or_create(text)
  File "/usr/lib/python2.7/site-packages/ChatterBot-0.8.6-py2.7.egg/chatterbot/trainers.py", line 48, in get_or_create
    statement = self.storage.find(temp_statement.text)
AttributeError: 'ChatBot' object has no attribute 'find'
`

Thank a lot

**Comment by gunthercox** [comment]
This error is the result of trying to run outdated code with the latest version of ChatterBot. Please take a look at the latest version of the documentation for examples.
